name: Push and Pull Translations
run-name: Push [${{ github.ref_name }}] ${{ github.event.after }}
on: 
  pull_request:
    types:
      - opened
    paths:
      - 'public/locales/en.json' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Lokalise CLI
        run: curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh
      
      - name: Push to Lokalise
        env:
          GITHUB_PREVIOUS_COMMIT: ${{ github.event.before }}
          GITHUB_CURRENT_COMMIT: ${{ github.event.after }}
          VAR_LOKALISE_API_TOKEN: ${{ secrets.API_TOKEN }}
          VAR_LOKALISE_PROJECT_ID: ${{ vars.PROJECT_ID }}
          ENV_LOKALISE_SOURCE_LANG_ISO: en
        run: |
             while read file 
             do 
                if [ -f $file ]
                then
                  ./bin/lokalise2 --token ${{ env.VAR_LOKALISE_API_TOKEN }} --project-id ${{ env.VAR_LOKALISE_PROJECT_ID }} file upload --file="${file}" --lang-iso ${{ env.ENV_LOKALISE_SOURCE_LANG_ISO }} --replace-modified --include-path --use-automations=true --cleanup-mode --poll-timeout 120s
                fi
             done < <(
             if [ -z ${{ env.GITHUB_CURRENT_COMMIT }} ]
             then
              git ls-files -- '**${{ env.ENV_LOKALISE_SOURCE_LANG_ISO }}.json'
             else
              git diff --name-only ${{ env.GITHUB_PREVIOUS_COMMIT }} ${{ env.GITHUB_CURRENT_COMMIT }} -- '**${{ env.ENV_LOKALISE_SOURCE_LANG_ISO }}.json'
             fi | awk NF)
      
      - name: Sleep for 10 seconds
        run: sleep 10
      
      - name: Create and Switch to New Branch
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git checkout -b lokalise/${{ github.run_number }}

      - name: Pull from Lokalise
        env: 
          VAR_LOKALISE_API_TOKEN: ${{ secrets.API_TOKEN }}
          VAR_LOKALISE_PROJECT_ID: ${{ vars.PROJECT_ID }}
          GH_TOKEN: ${{ github.token }}
        run: |
             ./bin/lokalise2 --token ${{ env.VAR_LOKALISE_API_TOKEN }} --project-id ${{ env.VAR_LOKALISE_PROJECT_ID }} file download --format json --filter-langs=de --original-filenames=true --directory-prefix=/
             echo "Listing .json files in ./public/locales"
             find ./public/locales -name "*.json"
      
      - name: Stage, Commit, and Push Changes
        run: |
          git add ./public/locales/de.json
          if [[ -z $(git status --untracked-files=no --porcelain) ]]
          then
            echo "No changes detected. No Commit."
          else
            git commit -m 'Translations update'
            git push --set-upstream origin lokalise/${{ github.run_number }}
          fi
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: lokalise/${{ github.run_number }}
          base: ${{ github.event.pull_request.base.ref }}
          title: 'Translations update from Lokalise'
          body: 'Translations updated.'